name: Deploy EnerLuz para EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copiar index.html para o EC2
        run: |
          scp -i ~/.ssh/deploy_key \
            index.html \
            ${{ secrets.EC2_USER }}@${{ secrets.HOST }}:/tmp/index.html

      - name: Mover arquivo e recarregar o Nginx
        run: |
          ssh -i ~/.ssh/deploy_key \
            ${{ secrets.EC2_USER }}@${{ secrets.HOST }} \
            "sudo mv /tmp/index.html /var/www/html/index.html && sudo systemctl reload nginx"
